### ISSUE TITLE
Avalara push data no exempt applied

### ISSUE THREAD

**Issue by krijn1981** [OCA/account-fiscal-rule#163]
We have tested avalara connector in serveral cases. (see attached document)
It looks like that exempt is not pushed with the API, strange becasue we have a pull of tax exempt data on res.partner. Are we doing something wrong? (I think not sure, that in code seeing that the push is exempted=None.
https://github.com/OCA/account-fiscal-rule/blob/13.0/account_avatax/models/avatax_rest_api.py#L199

[Exempted sales tax blurred.pdf](https://github.com/OCA/account-fiscal-rule/files/5924713/Exempted.sales.tax.blurred.pdf)

**Comment by dreispt** [comment]
Hello, I believe this issue happens when creating a new Invoice directly, as opposed to creating an Invoice from a Sales Order,

I set an Delivery Adress with an exemption status, and then created an Invoice for the customer.
The Exemption status fields were not populated:

![image](https://user-images.githubusercontent.com/1246629/113861496-32a1f080-979f-11eb-8114-03ce15920f05.png)

![image](https://user-images.githubusercontent.com/1246629/113861476-2ddd3c80-979f-11eb-9645-b97d0a42017d.png)
