### ISSUE TITLE
l10n_eu_oss: Odoo official One-Stop-Shop implementation released 

### ISSUE THREAD

**Issue by dreispt** [OCA/account-fiscal-rule#226]
The main commit is here: https://github.com/odoo/odoo/commit/d347eae1646639e2b346d404d1eb68ce9eac005c#diff-6299170bf4eb194cb23d4b799e0ce09b17a250b11e6eeb6aa3c58f63cea04c95

It is available in Odoo community, so I guess the OCA module should be considered deprecated.

**Comment by pedrobaeza** [comment]
I consider Odoo's one very limited, as they are constrained by the stability policy (I don't know why they haven't added a new module instead...). The main pitfall I see is that there's no reference on the tax to the OSS country it comes from, so having to mangle with tax names is a no-go for me.

**Comment by dreispt** [comment]
@pedrobaeza I didn't check the details, but if possible, our module should avoid overlapping standard features as much as possible, and just add the features we feel are missing.
Again, this needs a more detailed analysis to confirm if it is practical.

**Comment by pedrobaeza** [comment]
I did such analysis, and I don't see the possibility, and being very compact, I don't see why we should switch to the Odoo one in this case. Note that I'm always against duplicating features, but this case is different due to a lot of things. See some of my analysis here:

https://github.com/odoo/odoo/pull/72771#issuecomment-868615297

**Comment by HaraldPanten** [comment]
+1 @pedrobaeza 

IMHO, Odoo did a "botched job" because they realised that this new legislation was serious and obligatory too late. Because of that, they looked for a poor solution in order to get out of trouble.

As Pedro analised, this implementation in Odoo Community does not cover enough use cases, mainly because:

1- This legislation is only for B2C sales but user can not distinguish between end clients or companies.

2- Only general taxes can be propperly mapped but there are other taxes than general VAT. (reduced, super reduced...).

I wouldn't recommend to use Odoo's solution for OSS to any of my clients until it hasn't been improved enough.

@dreispt

**Comment by sergiocorato** [comment]
+1 @pedrobaeza 
Odoo Community implementation is, as they admit, 'limited'.

**Comment by dreispt** [comment]
Implemented, thank you for all the contributors, designing, implementing, reviewing and migrating through 11.0 to 14.0.
