### ISSUE TITLE
account_product_fiscal_classification overide l10n localization

### ISSUE THREAD

**Issue by bealdav** [OCA/account-fiscal-rule#80]
module: account_product_fiscal_classification
version: 10.0

**Steps to reproduce**
- install this module and l10n_fr (or another localization)

**Current behavior**
generic coa is installed instead of l10n_fr

**Expected behavior**
l10n_fr should be installed instead of coa

**Solution**
- remove coa from dependencies
- other suggestions ?

@legalsylvain

**Comment by legalsylvain** [comment]
Hi. I understand that l10n_generic_coa is installed when account_product_fiscal_classification is. (because of dependencies, usefull to make test ref : https://github.com/OCA/account-fiscal-rule/blob/10.0/account_product_fiscal_classification/demo/account_tax_template.yml#L9).

I don't understand why l10n_fr module can not be installed. Could you provide more precision ? 
regards.

Note : the same occures for account_fiscal_position_rule BTW.

**Comment by bealdav** [comment]
When i install a db from scratch with the 2 modules whether the order. I think i can find a workaround for my case but that don't solve initial problem.

I understand for the test. We should have a conditional depends, but it don't exists.

Have you an idea ?

**Comment by bealdav** [comment]
Finally with a lot of trials, I haven't found the best way to be sure to have l10n_fr installed instead of generic_coa.

I have a module named `dependency` which depends of all modules except `account_product_fiscal_classification`

and a module `custom` which depends of `account_product_fiscal_classification` and `dependency`,

When i install dependency first and then custom, it's ok
but when i install only custom, generic_coa is installed

Id dependency depends of account_prod_classif, it doesn't work.

@legalsylvain  Have you an idea of the workaround, to be sure the right coa is associated to the company ?

On my side I think, a way to solve it, is to create a module `account_product_fiscal_classification_test` and remove dependency on the first one.

Thanks

**Comment by legalsylvain** [comment]
Sorry, no idea on that point.

**Comment by bealdav** [comment]
Ok, thanks for your quick reply.

So do you accept my proposal to have a separate module for test purpose for both modules which contains these dependencies ?

Can I do a PR ?

**Comment by bealdav** [comment]
@legalsylvain do you accept a PR to have this plan ?

https://github.com/OCA/connector/tree/11.0/test_component
https://github.com/OCA/connector/tree/11.0/test_connector

Thanks for your answer.

**Comment by legalsylvain** [comment]
Hi @bealdav, 
thanks to investigate this problem. I don't have a clear point of view.

Solution 1 : remove dependency to generic_coa and update demo data. (not saw if it is a big work, the dependency is required here : https://github.com/OCA/account-fiscal-rule/blob/10.0/account_product_fiscal_classification/demo/account_tax_template.yml#L6
maybe creating just a new configurable_chart_template in the current module (without data, just an item) will fix the problem.)

Solution 2 : remove dependency to generic_coa and create a new module _test with the dependency to generic_coa.

I'm maybe most in favor of the solution 1, *if it is possible*. Otherwise, no problem to split the module into 2.

I think that @rvalyi could have a valid point of view, as the dependency is required by a feature he introduced (handle account.tax.template) I personaly don't use. 

regards.

**Comment by legalsylvain** [comment]
ping @rvalyi !

**Comment by legalsylvain** [comment]
@bealdav, thinking again on that point, I think splitting the module in two. (one for the code, and one for the test will be maybe the more simple).
Feel free to make a PR, I'l review quickly.

kind regards.

**Comment by bealdav** [comment]
Hi Sylvain,

I probably needs this module in v12.

I propose to make changes for v12 only because it's not a blocking issue if you install first the the right coa and then this module

Thanks to have analyzed this issue and answered.
